[package]
name = "nary-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
slab = "0.4.9"
uuid = { version = "1.8.0", features = ["v7"] }
